[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  # URLはNetlifyがビルド時に提供する環境変数なので、変数展開ではなく固定の文字列として設定する
  # 実際の値はNetlifyが環境ごとに設定する
  VITE_BASE_URL = "URL"
  # このnetlify.tomlはGit管理するため、シークレットはダッシュボードから登録する！

# Production context
# 本番環境
[context.production.environment]
  NODE_ENV = "production"

# Deploy Preview context
# 毎PR作成時にビルドされる一時的なプレビュー環境
[context.deploy-preview.environment]
  NODE_ENV = "production"

# Branch Deploy context
# main以外のブランチにpushしたときに自動でデプロイされるプレビュー環境
[context.branch-deploy.environment]
  NODE_ENV = "production"
